swagger: 2.0
info:
  version: "0.0.1"
  title: CRM SOAP App
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - text/xml
# format of the responses to the client (Accepts)
produces:
  - text/plain
x-a127-config: {}
x-volos-resources: {}
paths:
  /addCustomer/{fname}/{lname}:
    # binds a127 app logic to a route
    x-swagger-router-controller: customer
    x-volos-authorizations: {}
    x-volos-apply: {}
    get:
      description: Returns Adds a customer to the SOAP-based CRM System
      # used as the method name of the controller
      operationId: addCustomer
      parameters:
        - name: fname
          in: path
          description: The first name of the customer to add
          required: true
          type: string
        - name: lname
          in: path
          description: The last name of the customer to add
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: CustomerResponse
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: ErrorResponse
  /getCustomer/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: customer
    x-volos-authorizations: {}
    x-volos-apply: {}
    get:
      description: Returns Adds a customer to the SOAP-based CRM System
      # used as the method name of the controller
      operationId: getCustomer
      parameters:
        - name: id
          in: path
          description: The first name of the customer to add
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: CustomerResponse
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: ErrorResponse
# complex objects have schema definitions
definitions:
  CustomerResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
